webpack-contrib/url-loader

README.md
This took a while to track down and verify, had to look at the source,
then look at the Webpack docs which say "In the simple case, when only a
single loader is applied to the resource, the loader is called with one
parameter: the content of the resource file as string." That page
doesn't mention the `raw` option. Then discovered raw, discovered it was
a Buffer, and had to look up what Buffer.length is here:
https://nodejs.org/api/buffer.html#buffer_buf_length So I believe this
commit is correct.
=> Improving README by explicitly stating unit of measure for limit

package.json
The 1.2.x versions of [mime](https://github.com/broofa/node-mime) is 3 years old and lacks support for many common mime types today.
=> Bumb version of mime

README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra @SpaceK33z
=> Update README with -loader suffix on examples to reflect the change in Webpack 2

index.js
**What kind of change does this PR introduce?**
Refactoring
**Did you add tests for your changes?**
manual testing :smile: 
**If relevant, did you update the README?**
not required
**Summary**
Consistent getting `limit` options, also don't use 0 as default `limit` value because this is misleading when reading the code: if no `limit` encode all, if `limit` enable encode only files smaller than `limit`.
**Does this PR introduce a breaking change?**
No
**Other information**
not required
=> fix: don't default to `0` (`options.limit`)

index.js
Bugfix for strings not being base64 encoded. The specific issue is to do with happypack passing SVGs as strings instead of Buffers causes them to not be encoded properly.
=> fix: `String` not being `base64` encoded

index.js, options.json, package.json
=> feat(index): add options validation (`schema-utils`)

README.md
**What kind of change does this PR introduce?**
Documentation
**Did you add tests for your changes?**
not required
**If relevant, did you update the README?**
yep :smile: 
**Summary**
- Closes https://github.com/webpack-contrib/url-loader/issues/83
**Does this PR introduce a breaking change?**
not
**Other information**
not required
=> docs(README): remove confusing `prefix` option

README.md, index.js
**What kind of change does this PR introduce?**
Feature
**Did you add tests for your changes?**
no tests in repo
**If relevant, did you update the README?**
yes
**Summary**
Ref: https://github.com/webpack-contrib/url-loader/issues/82
**Does this PR introduce a breaking change?**
no
**Other information**
not required
=> feat: add `fallback` option (`options.fallback`)

package.json
**What kind of change does this PR introduce?**
Chore
**Did you add tests for your changes?**
not required
**If relevant, did you update the README?**
not required
**Summary**
Ref: https://github.com/broofa/node-mime/issues/168
**Does this PR introduce a breaking change?**
no
**Other information**
not required
=> chore(package): update `mime` v1.3.6...2.0.0

options.json
=> fix: allow use `limit` as `{String}`

src/index.js
Use `Buffer.from(string)` instead of deprecated `new Buffer(string)`.
Requires Node.js >= 4.5.0, but that seems to fit into current version requirements.
Refs:
https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor
=> fix(index): use `Buffer.from`  instead of deprecated `new Buffer`

README.md
Small extension to the readme because it was originally not clear to me how one can set the fallback loader options. Created on suggestion of @evilebottnawi in issue #118.
fixes #118
=> Readme: add example to set options for fallback loader

src/index.js, src/options.json, src/utils/normalizeFallback.js, test/options/__snapshots__/fallback.test.js.snap, test/options/fallback.test.js, test/utils/__snapshots__/normalizeFallback.test.js.snap, test/utils/normalizeFallback.test.js
It is now possible to explicitly specify options for the fallback loader.
The `fallback` option now behaves similar to [`module.rules.use`](https://webpack.js.org/configuration/module/#rule-use).
This 1.0.1-based configuration…
``` javascript
{
test: /\.(?:woff|woff2|eot|ttf|svg)$/,
use: {
loader: 'url-loader',
options: {
limit: 8192,
fallback: 'file-loader'
}
}
}
```
…can now be written as
``` javascript
{
test: /\.(?:woff|woff2|eot|ttf|svg)$/,
use: {
loader: 'url-loader',
options: {
limit: 8192,
fallback: {
loader: 'file-loader'
}
}
}
}
```
And as one would expect, that means options can be provided, as well…
``` javascript
{
test: /\.(?:woff|woff2|eot|ttf|svg)$/,
use: {
loader: 'url-loader',
options: {
limit: 8192,
fallback: {
loader: 'file-loader',
options: {
name: '[name].[ext]'
}
} …
```
=> feat(index): support fallback loader options (`options.fallback`)

test/__snapshots__/Errors.test.js.snap
The error ‒ and therefore the snapshot ‒ contains the line number of the validateOptions call. That line moves, so the snapshot is now updated.
=> Fixed a test

README.md
In the example `webpack.config.js`, the pattern `/\.(png|jpg|gif)$/` is used to select compatible images, but some images use `.JPG` instead of `.jpg`, and are thus not detected by webpack.
=> Support for `.JPG` extension added to example web pack config

package.json
This will allow url-loader to depend on new, compatible versions of schema-utils as they are released. The other dependencies of url-loader are declared this way. See https://github.com/webpack-contrib/url-loader/pull/136#issuecomment-412967621
n/a
=> chore(package): use caret range for `schema-utils` (`dependencies`)

src/utils/normalizeFallback.js, test/options/__snapshots__/fallback.test.js.snap, test/options/fallback.test.js, test/utils/__snapshots__/normalizeFallback.test.js.snap
Fixes #138 by passing on all non-`url-loader` options when defaulting to `file-loader` as the fallback.
This also implements the suggestion which was previously in a code comment to strip out url-loader specific options when passing them to the fallback - this shouldn't be a breaking change as they were never accepted by `file-loader`.
Should undo a breaking change for people who depended on options being passed on to `file-loader` 😹 
❤️
=> fix(utils/normalizeFallback): correctly pass all `options` to the default fallback (`file-loader`)

src/index.js
we don't support webpack@3 in this package
no
delete is very expensive operation (perf)
/cc @insin can you test this branch to avoid we fix problem https://github.com/webpack-contrib/url-loader/issues/138
=> refactor(index): remove unnecessary delete

package.json
It was unexpectedly introduced in https://github.com/webpack-contrib/url-loader/commit/9946374885ec01578ad692a386c82e08b3a9c1e7
See https://github.com/webpack-contrib/url-loader/commit/9946374885ec01578ad692a386c82e08b3a9c1e7#r30474904
- Fixes #147
=> fix(package): add support for `webpack =< v3.0.0` (`peerDependencies`)

lint-staged.config.js, package-lock.json, package.json, src/index.js, src/options.json, test/__snapshots__/validate-options.test.js.snap, test/validate-options.test.js
=> feat: improved validation error messages

package-lock.json, src/options.json, test/__snapshots__/validate-options.test.js.snap
Added 'description' field on esModule option and fixed security issue
=> fix(deps): fixed security issue and added description on esModule

README.md, package-lock.json, package.json, src/index.js
BREAKING CHANGE: migrate on `mime-types` package
Use official mime types package from jshttp
Yes, some extension can have other mime type
No
=> chore(deps): migrate on `mime-types` package
